### ISSUE TITLE
Delete project/server (from device)

### ISSUE THREAD

**Issue by Hustenbonbon** [mayflower/iWontPayAnyway#4]
Possibility to delete a single project or server, instead of **all** data on device

**Comment by Logarythms** [comment]
Support added in a64e9a9e146661c4a7e0de3aae5a6bf223b71abd & b918a35c1eb3dba107db9648f0d76184d4b48a8f, still needs to be exposed to UI

**Comment by Logarythms** [comment]
UI support added in 32d3b2d818f84c502725921fe87aa63fc5812521
